### ISSUE TITLE
Showcase example notebooks

### ISSUE THREAD

**Issue by stsievert** [jrbourbeau/pyunfold#94]
It'd be nice to have more integration with [the notebook examples][1]. This would (likely) include

* integrating the examples into the docs as static HTML pages
* integrating with Binder for executable notebooks

[1]:https://github.com/jrbourbeau/pyunfold/tree/bf1ce87a59e23e1fc30854e96aa4c63d0380bdf0/docs/source/notebooks

**Comment by stsievert** [comment]
For integrating with docs, I think [nbsphinx] is a good tool to look at. It's what several other projects use (including the project I'm involved with, Dask-ML).

[nbsphinx]:https://nbsphinx.readthedocs.io/

**Comment by jrbourbeau** [comment]
@stsievert thank you for the comments! Nice to see you here :) 

The example notebooks are currently rendered in the ["Advanced Techniques" section of the docs](https://jrbourbeau.github.io/pyunfold/advanced.html) using `nbsphinx` (e.g. https://jrbourbeau.github.io/pyunfold/notebooks/user_prior.html). 

Do you think it would be worth renaming that section of the docs "Examples" instead of "Advanced Techniques"? I'd like to add a couple of additional examples that cover less advanced topics anyways, so renaming that section to "Examples" may make more sense in the future anyways.

**Comment by fzeiser** [comment]
I think it wouldn't be bad to call it "Further Examples" or something like that. It took me a while to understand that the multivariate example is in there -- though I should have checked it earlier of course. 

Thumbs up also for the inclusion of more examples: That will make it even easier to see some typical  usages of the program as it is already now.

**Comment by stsievert** [comment]
> Do you think it would be worth renaming that section of the docs "Examples" instead of "Advanced Techniques"?

Good, it's only a renaming/reorganizing thing. I think it'd be good to have all the examples in one place. I think that place should be right below the installation documentation. Here's (some of) Dask's documentation layout, which has the same flavor:

<img width="159" alt="screen shot 2018-09-03 at 10 19 11 am" src="https://user-images.githubusercontent.com/1320475/44994131-c0d0ed00-af8c-11e8-9165-8da47cc56b8c.png">

I think to adapt this to PyUnfold, I'd like to see "array"/"bag"/etc renamed to "basic API tutorial"/"User defined prior"/etc

**Comment by fzeiser** [comment]
Thumbs up for #95 ;P.
